
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://125.46.13.246/fwpt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: p40xdP23H0NX
  swagger:
    base-package: com.zjwm.wyx
    enabled: true
  #redis
  redis:
    #redis机器ip
    host: 192.168.1.67
    #redis端口
    port: 6379
    timeout: 5000
    database: 0
    password: 123456
mybatis:
   mapper-locations: classpath:mapper/*/*.xml

#pagehelper分页
pagehelper:
   helperDialect: mysql

server:
  port: 8989



